default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: micross_otd_dev

test:
  <<: *default
  database: micross_otd_test

production:
  <<: *default
  database: micross_otd_prod
